<a href="https://colab.research.google.com/github/pooriag/applied_data_sience_course/blob/main/course1_Introduction_to_Data_Science_in_Python(week_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# working with csv files

In [ ]:
import csv

in here we use seaborn library for loading a csv file but other libraries can be used as well

In [ ]:
import seaborn as sns

In [ ]:
#loading csv file from dataset
df = sns.load_dataset("mpg")

In [ ]:
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa      

In [ ]:
for line in df:
  print(line)

mpg
cylinders
displacement
horsepower
weight
acceleration
model_year
origin
name


In [ ]:
csv_r = csv.reader(df)

print(next(csv_r))
print(df["mpg"][3])

['mpg']
16.0
['cylinders']


In [ ]:
csv_dict_r = csv.DictReader(df)
for line in csv_dict_r:
  print(line)

{'mpg': 'cylinders'}
{'mpg': 'displacement'}
{'mpg': 'horsepower'}
{'mpg': 'weight'}
{'mpg': 'acceleration'}
{'mpg': 'model_year'}
{'mpg': 'origin'}
{'mpg': 'name'}


with downloaded file

In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_reader = csv.reader(csv_file)

  print(csv_reader)

  print(next(csv_reader))
  print(next(csv_reader))

['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']
['2021', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '757,504', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)']


In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  print(next(csv_reader))
  print(next(csv_reader))

{'Year': '2021', 'Industry_aggregation_NZSIOC': 'Level 1', 'Industry_code_NZSIOC': '99999', 'Industry_name_NZSIOC': 'All industries', 'Units': 'Dollars (millions)', 'Variable_code': 'H01', 'Variable_name': 'Total income', 'Variable_category': 'Financial performance', 'Value': '757,504', 'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'}
{'Year': '2021', 'Industry_aggregation_NZSIOC': 'Level 1', 'Industry_code_NZSIOC': '99999', 'Industry_name_NZSIOC': 'All industries', 'Units': 'Dollars (millions)', 'Variable_code': 'H04', 'Variable_name': 'Sales, government funding, grants and subsidies', 'Variable_category': 'Financial performance', 'Value': '674,890', 'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'}


In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_l = list(csv.DictReader(csv_file))



In [ ]:
#csv_l

In [ ]:
len(csv_l)

41715

In [ ]:
csv_l[:3]

[{'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  'Industry_code_NZSIOC': '99999',
  'Industry_name_NZSIOC': 'All industries',
  'Units': 'Dollars (millions)',
  'Variable_code': 'H01',
  'Variable_name': 'Total income',
  'Variable_category': 'Financial performance',
  'Value': '757,504',
  'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'},
 {'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  'Industry_code_NZSIOC': '99999',
  'Industry_name_NZSIOC': 'All industries',
  'Units': 'Dollars (millions)',
  'Variable_code': 'H04',
  'Variable_name': 'Sales, government funding, grants and subsidies',
  'Variable_category': 'Financial performance',
  'Value': '674,890',
  'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'},
 {'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  '

In [ ]:
from functools import cache
#values mean

def value_converter(s):
  j = ''
  for i in s.split(","):
    j += i

  try:
    return int(j)

  except:
    return 0

sum(value_converter(i["Value"]) for i in csv_l) / len(csv_l)

30023.976459307203

# Dates and times(introduction)

In [ ]:
import time as tm
import datetime as dt

In [ ]:
time = tm.time()
time

1694073837.8740335

**converting to a readble format**

In [ ]:
date = dt.datetime.fromtimestamp(time)
date

datetime.datetime(2023, 9, 7, 8, 3, 57, 874033)

analysing times with specified distance

In [ ]:
delta = dt.timedelta(days =5)

In [ ]:
today = dt.date.today()

In [ ]:
today - delta

datetime.date(2023, 9, 2)

# map()

In [ ]:
# @title finding max between two list

lst1 = [4.6, 7.3, 2]
lst2 = [9.5, 6.73, 10]

list(map(max, lst1, lst2))

[9.5, 7.3, 10]

#lambda

In [ ]:
my_annonimous_func = lambda inp : inp ** 2

my_annonimous_func(5)

25

#list comprehensions

In [ ]:
letters = "abc"
digits = "123"

ids = [(letters[i] + letters[j] + k) for i in range(len(letters)) for j in range(i, len(letters)) for k in digits]
print(ids)
print(len(ids))

['aa1', 'aa2', 'aa3', 'ab1', 'ab2', 'ab3', 'ac1', 'ac2', 'ac3', 'bb1', 'bb2', 'bb3', 'bc1', 'bc2', 'bc3', 'cc1', 'cc2', 'cc3']
18


#Numpy

In [ ]:
#@title importing libraries
import numpy as np
import math

In [ ]:
#@title creating arrays

test_array = np.array([1, 2, 3, 4])
print(test_array)
print(test_array.ndim)

[1 2 3 4]
1


In [ ]:
#@title 2d array

two_d_array = np.array([[1, 2, 3], [5, 3, 7.9]])

print(two_d_array.ndim)

2


In [ ]:
#@title shape of an array

two_d_array.shape

(2, 3)

In [ ]:
two_d_array.dtype

dtype('float64')

##place holders

In [ ]:
#@title filling array with ones

np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#@title filling array with zeros

np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#@title filling with random uniform numbers between 0 up to 1

np.random.rand(2, 3)

array([[0.8580616 , 0.11067739, 0.4607176 ],
       [0.36152515, 0.49887376, 0.56040644]])

##sequence of numbers

In [ ]:
#@title sequence of numbers with defines step(end excluded)

np.arange(10, 50, 2)# even numbers from 10 to 48

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
#@title sequence of numers(float) with defined quantitie

np.linspace(0, 2, 15)# generaiting 15 float numbers betweeen 0 to 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

##Array oparaitions

So, we can do many things on arrays, such as mathematical manipulation, addition, subtraction, square, exponents, as well as Boolean arrays, which are binary values. And we can also do matrix manipulations, such as product transpose, inverse and so forth

In [ ]:
#@title arithmetic applied on asrray elementwise

a = np.array([[1, 2, 3], [3, 5, 6]])
b = np.array([[4.6, 2.3, 7.8], [5, 6.2, 9.0]])

print("sum of a and b : {}".format(a + b))

print("subtraction of b and : {}".format(b - a))

print("a to the power of b :{}".format(a ** b))

print("multiplicationn of a and b : {}".format(a * b))

sum of a and b : [[ 5.6  4.3 10.8]
 [ 8.  11.2 15. ]]
subtraction of b and : [[3.6 0.3 4.8]
 [2.  1.2 3. ]]
a to the power of b :[[1.00000000e+00 4.92457765e+00 5.26678739e+03]
 [2.43000000e+02 2.15582760e+04 1.00776960e+07]]
multiplicationn of a and b : [[ 4.6  4.6 23.4]
 [15.  31.  54. ]]


In [ ]:
#@title non_elemnt wise matrix multiplication

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[6, 7], [9, 0]])

print(m1@m2)

[[24  7]
 [54 21]]


###example
convert array of farenheit to celcius

In [ ]:
farenheit = np.array([10, 0, -0.5, 3, 5])#creating an array of tempreture in farenheit

celcius = (farenheit - 32) * (5 / 9)

print(celcius)

[-12.22222222 -17.77777778 -18.05555556 -16.11111111 -15.        ]


###boolean array
Another useful and important manipulation is the Boolean array. We can apply an operator on an array and a Boolean array will be returned for any element in the original with true being emitted if it meets the condition. For instance, if we want to get a Boolean array to check the Celsius degrees that are greater than minus 20 degrees, we will just say Celsius is greater than minus 20

In [ ]:
print(celcius < -17)

[False  True  True False False]


###aggregation functions

Now, numpy arrays also have an interesting aggregation functions on them, such as sum, max, min and mean

In [ ]:
array1 = np.array([[1, 3], 4])

array2 = np.array([[3, 3], [9, 5]])

array3 = np.array([[4, 5, 6], [7, 6]])

<ipython-input-18-370403693bad>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1 = np.array([[1, 3], 4])
<ipython-input-18-370403693bad>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array3 = np.array([[4, 5, 6], [7, 6]])


In [ ]:
#@title sum()

print(array3)
print(array3.sum())

print(array2)
print(array2.sum())

print(array1)
print(array1.sum())

[list([4, 5, 6]) list([7, 6])]
[4, 5, 6, 7, 6]
[[3 3]
 [9 5]]
20
[list([1, 3]) 4]


TypeError: ignored

In [ ]:
#@title max and min

print(array2)
print(array2.min(), array2.max())

print(array3)#[[4, 5, 6], [7, 6]]
print(array3.min(), array3.max())

array4 = np.array([[7, 6, 8], [7, 6]])
print(array4.min(), array4.max())

print(array1)
print(array1.min(), array1.max())

[[3 3]
 [9 5]]
3 9
[list([4, 5, 6]) list([7, 6])]
[4, 5, 6] [7, 6]
[7, 6] [7, 6, 8]
[list([1, 3]) 4]


<ipython-input-34-c842755f449c>:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array4 = np.array([[7, 6, 8], [7, 6]])


TypeError: ignored

In [ ]:
#@title mean()

print(array2)
print(array2.mean())

print(array3)
print(array3.mean())


print(array1)
print(array1.mean())

[[3 3]
 [9 5]]
5.0
[list([4, 5, 6]) list([7, 6])]
[2.  2.5 3.  3.5 3. ]
[list([1, 3]) 4]


TypeError: ignored

##indexing , slicing and itteraiting

###indexing

In [ ]:
array = np.array([[1, 2, 3], [2, 4, 1], [3, 14, 13.2]])

In [ ]:
array[1, 2]

1.0

In [ ]:
array[[0, 1], [2, 1]]

array([3., 4.])

####boolean indexing

In [ ]:
array[array >= 4]

array([ 4. , 14. , 13.2])

###slicing

It's important to realize that a slice of an array is a view into the same data. This is really important, this is called passing by reference. So, modifying the sub array will consequently modify the original array as well.

In [ ]:
array = np.array([[1, 2, 3], [2, 4, 1], [3, 14, 13.2]])

In [ ]:
array[0]

array([1., 2., 3.])

In [ ]:
array[:, 2:]

array([[ 3. ],
       [ 1. ],
       [13.2]])

In [ ]:
a = array[:, 2:]

a[1,0] = 100

array

array([[  1. ,   2. ,   3. ],
       [  2. ,   4. , 100. ],
       [  3. ,  14. ,  13.2]])

## working with datasets

In [ ]:
wines_data = np.genfromtxt("files/course1/winequality-red.csv", delimiter=';', skip_header=True)

In [ ]:
wines_data

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [ ]:
wines_data[:, 0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [ ]:
wines_data[:, :1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]])

In [ ]:
wines_data

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [ ]:
wines_data[:, [0, -1]]

array([[7.4, 5. ],
       [7.8, 5. ],
       [7.8, 5. ],
       ...,
       [6.3, 6. ],
       [5.9, 5. ],
       [6. , 6. ]])

In [ ]:
quality = wines_data[:, -1]

quality

array([5., 5., 5., ..., 6., 5., 6.])

In [ ]:
q_mean = quality.mean()

q_mean

5.6360225140712945

In [ ]:
quality2 = wines_data[:, -1:]

quality2

array([[5.],
       [5.],
       [5.],
       ...,
       [6.],
       [5.],
       [6.]])

In [ ]:
quality2.mean() == q_mean

True

In [ ]:
wines_data.dtype

dtype('float64')

In [ ]:
admission_data = np.genfromtxt("files/course1/Admission_Predict.csv", delimiter=",", skip_header=True,
                               names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))

admission_data[:4]

array([(1., 337., 118., 4., 4.5, 4.5, 9.65, 1., 0.92),
       (2., 324., 107., 4., 4. , 4.5, 8.87, 1., 0.76),
       (3., 316., 104., 3., 3. , 3.5, 8.  , 1., 0.72),
       (4., 322., 110., 3., 3.5, 2.5, 8.67, 1., 0.8 )],
      dtype=[('Serial_No', '<f8'), ('GRE_Score', '<f8'), ('TOEFL_Score', '<f8'), ('University_Rating', '<f8'), ('SOP', '<f8'), ('LOR', '<f8'), ('CGPA', '<f8'), ('Research', '<f8'), ('Chance_of_Admit', '<f8')])

In [ ]:
admission_data.dtype

dtype([('Serial_No', '<f8'), ('GRE_Score', '<f8'), ('TOEFL_Score', '<f8'), ('University_Rating', '<f8'), ('SOP', '<f8'), ('LOR', '<f8'), ('CGPA', '<f8'), ('Research', '<f8'), ('Chance_of_Admit', '<f8')])

In [ ]:
admission_data = np.genfromtxt("files/course1/Admission_Predict.csv", delimiter=",", skip_header=True,
                               names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'), dtype=None)

In [ ]:
admission_data.dtype

dtype([('Serial_No', '<i8'), ('GRE_Score', '<i8'), ('TOEFL_Score', '<i8'), ('University_Rating', '<i8'), ('SOP', '<f8'), ('LOR', '<f8'), ('CGPA', '<f8'), ('Research', '<i8'), ('Chance_of_Admit', '<f8')])

In [ ]:
admission_data.shape

(400,)

In [ ]:
sliced = admission_data['CGPA']

sliced.shape

(400,)

In [ ]:
sliced[:3]

sliced

array([9.65, 8.87, 8.  , 8.67, 8.21, 9.34, 8.2 , 7.9 , 8.  , 8.6 , 8.4 ,
       9.  , 9.1 , 8.  , 8.2 , 8.3 , 8.7 , 8.  , 8.8 , 8.5 , 7.9 , 8.4 ,
       9.5 , 9.7 , 9.8 , 9.6 , 8.8 , 7.5 , 7.2 , 7.3 , 8.1 , 8.3 , 9.4 ,
       9.6 , 9.8 , 9.2 , 8.4 , 7.8 , 7.5 , 7.7 , 8.  , 8.2 , 8.5 , 9.1 ,
       9.4 , 9.1 , 9.3 , 9.7 , 8.85, 8.4 , 8.3 , 7.9 , 8.  , 8.1 , 8.  ,
       7.7 , 7.4 , 7.6 , 6.8 , 8.3 , 8.1 , 8.2 , 8.2 , 8.5 , 8.7 , 8.92,
       9.02, 8.64, 9.22, 9.16, 9.64, 9.76, 9.45, 9.04, 8.9 , 8.56, 8.72,
       8.22, 7.54, 7.36, 8.02, 9.5 , 9.22, 9.36, 9.45, 8.66, 8.42, 8.28,
       8.14, 8.76, 7.92, 7.66, 8.03, 7.88, 7.66, 7.84, 8.  , 8.96, 9.24,
       8.88, 8.46, 8.12, 8.25, 8.47, 9.05, 8.78, 9.18, 9.46, 9.38, 8.64,
       8.48, 8.68, 8.34, 8.56, 8.45, 9.04, 8.62, 7.46, 7.28, 8.84, 9.56,
       9.48, 8.36, 8.22, 8.47, 8.66, 9.32, 8.71, 9.1 , 9.35, 9.76, 8.65,
       8.56, 8.78, 9.28, 8.77, 8.45, 8.16, 9.08, 9.12, 9.15, 9.36, 9.44,
       9.92, 8.96, 8.64, 8.48, 9.11, 9.8 , 8.26, 9.

In [ ]:
mask = admission_data['Research'] == True

mask[:5]

array([ True,  True,  True,  True, False])

In [ ]:
admission_data[:5]#-2 row is research boolean

array([(1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65)],
      dtype=[('Serial_No', '<i8'), ('GRE_Score', '<i8'), ('TOEFL_Score', '<i8'), ('University_Rating', '<i8'), ('SOP', '<f8'), ('LOR', '<f8'), ('CGPA', '<f8'), ('Research', '<i8'), ('Chance_of_Admit', '<f8')])

In [ ]:
masked_data = admission_data[mask]

masked_data[:5]

array([(1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 )],
      dtype=[('Serial_No', '<i8'), ('GRE_Score', '<i8'), ('TOEFL_Score', '<i8'), ('University_Rating', '<i8'), ('SOP', '<f8'), ('LOR', '<f8'), ('CGPA', '<f8'), ('Research', '<i8'), ('Chance_of_Admit', '<f8')])

#regular expressions

In [5]:
#@title importimg library

import re

In [6]:
sample_string = """
abcdefghigklmnop
ABCDEFGHIJKLMNOP
123456789
"""

In [7]:
print(sample_string[0])

##raw string
when you put r at first of the string we call that the raw string and it causes complier to dont handle things like \n \t and ect in an special way.

In [8]:
s = '\thi'
print(s)

	hi


In [9]:
s = r'\thi'
print(s)

\thi


##searching for a literal string(case sensitive)

In [10]:

pattern = re.compile(r'abc')

matches = pattern.finditer(sample_string)

In [11]:
for m in matches:
  print(m)

<re.Match object; span=(1, 4), match='abc'>


##special characters

In [12]:
pattern = re.compile(r'.')

matches = pattern.finditer(sample_string)

for m in matches:
  print(m)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='g'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(18, 19), match='A'>
<re.Match object; span=(19, 20), match='B'>
<re.Match object; span=(20, 21), match='C'>
<re.Match object; span=(21, 22), match='D'>
<re.Match object; span=(22, 23), match='E'>
<re.Match object; span=(23, 24), match='F'>
<re.Match object; span=(24, 25), match='G'>
<re.M

because dot is an special character we need to scape it in order to just search for dots.

In [13]:
s_2 = "abcdsdldmac.,claclaaka[pkp..]"

pattern = re.compile(r'\.')

matches = pattern.finditer(s_2)

for m in matches:
  print(m)

<re.Match object; span=(11, 12), match='.'>
<re.Match object; span=(26, 27), match='.'>
<re.Match object; span=(27, 28), match='.'>


##meta charaters

In [14]:
sample_string = '''
ab
AB
12
.
/
\

:
'''

In [15]:
def print_matches(s):
  pattern = re.compile(r'{}'.format(s))

  matches = pattern.finditer(sample_string)

  for m in matches:
   print(m)


In [16]:
#@title . -> all characters except new lines
print_matches('.')

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(4, 5), match='A'>
<re.Match object; span=(5, 6), match='B'>
<re.Match object; span=(7, 8), match='1'>
<re.Match object; span=(8, 9), match='2'>
<re.Match object; span=(10, 11), match='.'>
<re.Match object; span=(12, 13), match='/'>
<re.Match object; span=(15, 16), match=':'>


In [17]:
#@title \d -> digits

print_matches('\d')

<re.Match object; span=(7, 8), match='1'>
<re.Match object; span=(8, 9), match='2'>


In [18]:
#@title \D -> all none digits characters
print_matches('\D')

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='\n'>
<re.Match object; span=(4, 5), match='A'>
<re.Match object; span=(5, 6), match='B'>
<re.Match object; span=(6, 7), match='\n'>
<re.Match object; span=(9, 10), match='\n'>
<re.Match object; span=(10, 11), match='.'>
<re.Match object; span=(11, 12), match='\n'>
<re.Match object; span=(12, 13), match='/'>
<re.Match object; span=(13, 14), match='\n'>
<re.Match object; span=(14, 15), match='\n'>
<re.Match object; span=(15, 16), match=':'>
<re.Match object; span=(16, 17), match='\n'>


In [19]:
#@title \w -> word characters (a-z, A-Z, 0-9, _)

print_matches('\w')

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(4, 5), match='A'>
<re.Match object; span=(5, 6), match='B'>
<re.Match object; span=(7, 8), match='1'>
<re.Match object; span=(8, 9), match='2'>


In [20]:
#@title \W -> none word characters

print_matches('\W')

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(3, 4), match='\n'>
<re.Match object; span=(6, 7), match='\n'>
<re.Match object; span=(9, 10), match='\n'>
<re.Match object; span=(10, 11), match='.'>
<re.Match object; span=(11, 12), match='\n'>
<re.Match object; span=(12, 13), match='/'>
<re.Match object; span=(13, 14), match='\n'>
<re.Match object; span=(14, 15), match='\n'>
<re.Match object; span=(15, 16), match=':'>
<re.Match object; span=(16, 17), match='\n'>


In [21]:
#@title \s -> white space(space, tab, new line)

print_matches('\s')

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(3, 4), match='\n'>
<re.Match object; span=(6, 7), match='\n'>
<re.Match object; span=(9, 10), match='\n'>
<re.Match object; span=(11, 12), match='\n'>
<re.Match object; span=(13, 14), match='\n'>
<re.Match object; span=(14, 15), match='\n'>
<re.Match object; span=(16, 17), match='\n'>


In [22]:
#@title \S -> note white space character

print_matches('\S')

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(4, 5), match='A'>
<re.Match object; span=(5, 6), match='B'>
<re.Match object; span=(7, 8), match='1'>
<re.Match object; span=(8, 9), match='2'>
<re.Match object; span=(10, 11), match='.'>
<re.Match object; span=(12, 13), match='/'>
<re.Match object; span=(15, 16), match=':'>


In [23]:
#@title \b -> word boundry

##it findes specified pattern that starts at start of a words

print_matches(r'\ba')
print('\n')
print_matches(r'\bb')

<re.Match object; span=(1, 2), match='a'>




In [24]:
#@title \B -> not a word boundry

print(sample_string + '\n')

print_matches(r'\Bb')
print_matches(r'\Ba')


ab
AB
12
.
/

:


<re.Match object; span=(2, 3), match='b'>


In [25]:
#@title ^ -> beginnig of a string

print_matches(r'^a')

print_matches(r'^\n')

<re.Match object; span=(0, 1), match='\n'>


In [26]:
#@title $ -> end of string

print_matches(r'$\n')

<re.Match object; span=(16, 17), match='\n'>


In [29]:
example_string = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ac leo auctor
, 123-456-789, tempor elit. Quisque eu 987.654.321. Morbi lacinia 555-444-333,
ullamcorper metus. Ut 111-222-333. Nunc tempus 777-888-999. Vestibulum 444-555-666.
 Sed lobortis 222-333-444, libero at. Phasellus 666-777-888, risus eget. Vivamus 999-888-777.'''


In [30]:
pattern = re.compile(r'\d\d\d[.-]\d\d\d[.-]\d\d\d')

matches = pattern.finditer(example_string)

for m in matches:
  print(m)

<re.Match object; span=(79, 90), match='123-456-789'>
<re.Match object; span=(116, 127), match='987.654.321'>
<re.Match object; span=(143, 154), match='555-444-333'>
<re.Match object; span=(179, 190), match='111-222-333'>
<re.Match object; span=(204, 215), match='777-888-999'>
<re.Match object; span=(228, 239), match='444-555-666'>
<re.Match object; span=(255, 266), match='222-333-444'>
<re.Match object; span=(289, 300), match='666-777-888'>
<re.Match object; span=(322, 333), match='999-888-777'>


In [35]:
#@title how to specify a range of characters

s = '''1234566788809472352
abcd'''

pattern = re.compile(r'[1-3]')

matches = pattern.finditer(s)

for m in matches:
  print(m)

pattern = re.compile(r'[^1-3]')

matches = pattern.finditer(s)

print("\n\n")

for m in matches:
  print(m)

<re.Match object; span=(0, 1), match='1'>
<re.Match object; span=(1, 2), match='2'>
<re.Match object; span=(2, 3), match='3'>
<re.Match object; span=(15, 16), match='2'>
<re.Match object; span=(16, 17), match='3'>
<re.Match object; span=(18, 19), match='2'>



<re.Match object; span=(3, 4), match='4'>
<re.Match object; span=(4, 5), match='5'>
<re.Match object; span=(5, 6), match='6'>
<re.Match object; span=(6, 7), match='6'>
<re.Match object; span=(7, 8), match='7'>
<re.Match object; span=(8, 9), match='8'>
<re.Match object; span=(9, 10), match='8'>
<re.Match object; span=(10, 11), match='8'>
<re.Match object; span=(11, 12), match='0'>
<re.Match object; span=(12, 13), match='9'>
<re.Match object; span=(13, 14), match='4'>
<re.Match object; span=(14, 15), match='7'>
<re.Match object; span=(17, 18), match='5'>
<re.Match object; span=(19, 20), match='\n'>
<re.Match object; span=(20, 21), match='a'>
<re.Match object; span=(21, 22), match='b'>
<re.Match object; span=(22, 23), match='c'>
<re

##quantifiers

In [44]:
samp = '''12345abc2lds254'''

In [45]:
def print_m(s):
  pattern = re.compile(s)

  matches = pattern.finditer(samp)

  for m in matches:

    print(m)

In [46]:
#@title * -> 0 or more

print_m(r'\d*')

<re.Match object; span=(0, 5), match='12345'>
<re.Match object; span=(5, 5), match=''>
<re.Match object; span=(6, 6), match=''>
<re.Match object; span=(7, 7), match=''>
<re.Match object; span=(8, 9), match='2'>
<re.Match object; span=(9, 9), match=''>
<re.Match object; span=(10, 10), match=''>
<re.Match object; span=(11, 11), match=''>
<re.Match object; span=(12, 15), match='254'>
<re.Match object; span=(15, 15), match=''>


In [47]:
#@title + -> 1 or more

print_m(r'\d+')

<re.Match object; span=(0, 5), match='12345'>
<re.Match object; span=(8, 9), match='2'>
<re.Match object; span=(12, 15), match='254'>


In [48]:
#@title ? -> 0 or one

print_m(r'\d?')

<re.Match object; span=(0, 1), match='1'>
<re.Match object; span=(1, 2), match='2'>
<re.Match object; span=(2, 3), match='3'>
<re.Match object; span=(3, 4), match='4'>
<re.Match object; span=(4, 5), match='5'>
<re.Match object; span=(5, 5), match=''>
<re.Match object; span=(6, 6), match=''>
<re.Match object; span=(7, 7), match=''>
<re.Match object; span=(8, 9), match='2'>
<re.Match object; span=(9, 9), match=''>
<re.Match object; span=(10, 10), match=''>
<re.Match object; span=(11, 11), match=''>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(13, 14), match='5'>
<re.Match object; span=(14, 15), match='4'>
<re.Match object; span=(15, 15), match=''>


In [49]:
#@title {n} -> n of specified character

print_m(r'\d{2}')

<re.Match object; span=(0, 2), match='12'>
<re.Match object; span=(2, 4), match='34'>
<re.Match object; span=(12, 14), match='25'>


In [51]:
#@title {n,m} -> a range from n to m

print_m(r'\d{2,4}')

<re.Match object; span=(0, 4), match='1234'>
<re.Match object; span=(12, 15), match='254'>


##example
match al the names

In [84]:
s = '''
Mr. Golestani
Ms Ahmadi
Mrs. Maghsoodi
Ms Jahanbani
Mr T'''

pattern = re.compile(r'(Mr|Ms|Mrs)\.?\s[A-Z]\w*')

mathces = pattern.finditer(s)

for m in matches:
  print(m)

'''results -->>

<re.Match object; span=(1, 14), match='Mr. Golestani'>
<re.Match object; span=(15, 24), match='Ms Ahmadi'>
<re.Match object; span=(25, 39), match='Mrs. Maghsoodi'>
<re.Match object; span=(40, 52), match='Ms Jahanbani'>
<re.Match object; span=(53, 57), match='Mr T'>

'''

"results -->>\n\n<re.Match object; span=(1, 14), match='Mr. Golestani'>\n<re.Match object; span=(15, 24), match='Ms Ahmadi'>\n<re.Match object; span=(25, 39), match='Mrs. Maghsoodi'>\n<re.Match object; span=(40, 52), match='Ms Jahanbani'>\n<re.Match object; span=(53, 57), match='Mr T'>\n\n"

##example
match emails

In [107]:
s = '''
randomuser1@gmail.com
example1234@gmail.com
user4321@gmail.com
testemail567@gmail.com
random12345@gmail.com
email_test678@gmail.com
userexample789@gmail.edu
gmail-test123@my-work.com
randomemail987@gmail.com
exampleuser456@gmail.com
'''

In [108]:
pattern = re.compile(r'[-_.0-9A-Za-z]+@[-A-Za-z]+\.(com|edu)')

In [109]:
matches = pattern.finditer(s)

In [110]:
for m in matches:
  print(m)

<re.Match object; span=(1, 22), match='randomuser1@gmail.com'>
<re.Match object; span=(23, 44), match='example1234@gmail.com'>
<re.Match object; span=(45, 63), match='user4321@gmail.com'>
<re.Match object; span=(64, 86), match='testemail567@gmail.com'>
<re.Match object; span=(87, 108), match='random12345@gmail.com'>
<re.Match object; span=(109, 132), match='email_test678@gmail.com'>
<re.Match object; span=(133, 157), match='userexample789@gmail.edu'>
<re.Match object; span=(158, 183), match='gmail-test123@my-work.com'>
<re.Match object; span=(184, 208), match='randomemail987@gmail.com'>
<re.Match object; span=(209, 233), match='exampleuser456@gmail.com'>


##getting informaition from groups

In [127]:
urls = '''
https://www.google.com
http://coreyms.com
https://youtube.com
https://www.nasa.gov
'''

In [131]:
pattern = re.compile(r'https?://(www.)?(\w+)(\.\w+)')

In [132]:
matches = pattern.finditer(urls)

In [133]:
for m in matches:
  print(m.group(0), m.group(1), m.group(2), m.group(3))

https://www.google.com www. google .com
http://coreyms.com None coreyms .com
https://youtube.com None youtube .com
https://www.nasa.gov www. nasa .gov


In [135]:
#@title back refrence

subed_urls = pattern.sub(r'www.\2\3', urls)

print(subed_urls)


www.google.com
www.coreyms.com
www.youtube.com
www.nasa.gov



##other methodes of re library

In [136]:
s = 'abcabbca'

In [138]:
re.search('a', s)

<re.Match object; span=(0, 1), match='a'>

In [139]:
re.findall('a', s)

['a', 'a', 'a']

In [140]:
re.split('a', s)

['', 'bc', 'bbc', '']

##named groups and look ahead

In [164]:
s = '''
Mr. Golestani
Ms Ahmadi
Mrs. Maghsoodi
Ms Jahanbani
Mr T'''

In [184]:
pattern = re.compile(r'(?P<sit>Mr|Mrs|Ms)\.?\s(?=\w+)')

In [185]:
matches = pattern.finditer(s)

In [186]:
for m in matches:
  print(m.groupdict())

{'sit': 'Mr'}
{'sit': 'Ms'}
{'sit': 'Mrs'}
{'sit': 'Ms'}
{'sit': 'Mr'}


you can write regex with ''' ''' so that is more readble but first you nedd to set coresponding flag to true and after that use \ for spaces or new line ore use \s

##example

In [249]:
s = """
121.104.130.220 - dach6856 [21/Jun/2019:15:47:11 -0700] "GET /infomediaries/e-business/metrics/interfaces HTTP/1.0" 201 15366
"""

In [250]:
matches = re.finditer(pattern, s, flags=re.VERBOSE)

In [251]:
pattern = '''

    (?P<host>\d{3}\.\d{3}\.\d{3}\.\d{3})\ -\
    (?P<user_name>-|[a-z0-9]*)\
    \[(?P<time>\d{2}\/[A-Z][a-z]*\/\d{4}:\d{2}:\d{2}:\d{2}\ [-]\d{4})\]\
    "(?P<request>[A-Z]*\ [^ ]*\ [^"]*)
    '''

In [252]:
for m in matches:
  print(m.groupdict())

{'host': '121.104.130.220', 'user_name': 'dach6856', 'time': '21/Jun/2019:15:47:11 -0700', 'request': 'GET /infomediaries/e-business/metrics/interfaces HTTP/1.0'}
