<a href="https://colab.research.google.com/github/pooriag/applied_data_sience_course/blob/main/course1_Introduction_to_Data_Science_in_Python(week_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# working with csv files

In [ ]:
import csv

in here we use seaborn library for loading a csv file but other libraries can be used as well

In [ ]:
import seaborn as sns

In [ ]:
#loading csv file from dataset
df = sns.load_dataset("mpg")

In [ ]:
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa      

In [ ]:
for line in df:
  print(line)

mpg
cylinders
displacement
horsepower
weight
acceleration
model_year
origin
name


In [ ]:
csv_r = csv.reader(df)

print(next(csv_r))
print(df["mpg"][3])

['mpg']
16.0
['cylinders']


In [ ]:
csv_dict_r = csv.DictReader(df)
for line in csv_dict_r:
  print(line)

{'mpg': 'cylinders'}
{'mpg': 'displacement'}
{'mpg': 'horsepower'}
{'mpg': 'weight'}
{'mpg': 'acceleration'}
{'mpg': 'model_year'}
{'mpg': 'origin'}
{'mpg': 'name'}


with downloaded file

In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_reader = csv.reader(csv_file)

  print(csv_reader)

  print(next(csv_reader))
  print(next(csv_reader))

['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']
['2021', 'Level 1', '99999', 'All industries', 'Dollars (millions)', 'H01', 'Total income', 'Financial performance', '757,504', 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)']


In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  print(next(csv_reader))
  print(next(csv_reader))

{'Year': '2021', 'Industry_aggregation_NZSIOC': 'Level 1', 'Industry_code_NZSIOC': '99999', 'Industry_name_NZSIOC': 'All industries', 'Units': 'Dollars (millions)', 'Variable_code': 'H01', 'Variable_name': 'Total income', 'Variable_category': 'Financial performance', 'Value': '757,504', 'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'}
{'Year': '2021', 'Industry_aggregation_NZSIOC': 'Level 1', 'Industry_code_NZSIOC': '99999', 'Industry_name_NZSIOC': 'All industries', 'Units': 'Dollars (millions)', 'Variable_code': 'H04', 'Variable_name': 'Sales, government funding, grants and subsidies', 'Variable_category': 'Financial performance', 'Value': '674,890', 'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'}


In [ ]:
with open("annual-enterprise-survey-2021-financial-year-provisional-csv.csv", 'r') as csv_file:
  csv_l = list(csv.DictReader(csv_file))



In [48]:
#csv_l

In [ ]:
len(csv_l)

41715

In [ ]:
csv_l[:3]

[{'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  'Industry_code_NZSIOC': '99999',
  'Industry_name_NZSIOC': 'All industries',
  'Units': 'Dollars (millions)',
  'Variable_code': 'H01',
  'Variable_name': 'Total income',
  'Variable_category': 'Financial performance',
  'Value': '757,504',
  'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'},
 {'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  'Industry_code_NZSIOC': '99999',
  'Industry_name_NZSIOC': 'All industries',
  'Units': 'Dollars (millions)',
  'Variable_code': 'H04',
  'Variable_name': 'Sales, government funding, grants and subsidies',
  'Variable_category': 'Financial performance',
  'Value': '674,890',
  'Industry_code_ANZSIC06': 'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'},
 {'Year': '2021',
  'Industry_aggregation_NZSIOC': 'Level 1',
  '

In [ ]:
from functools import cache
#values mean

def value_converter(s):
  j = ''
  for i in s.split(","):
    j += i

  try:
    return int(j)

  except:
    return 0

sum(value_converter(i["Value"]) for i in csv_l) / len(csv_l)

30023.976459307203

# Dates and times(introduction)

In [ ]:
import time as tm
import datetime as dt

In [ ]:
time = tm.time()
time

1694073837.8740335

**converting to a readble format**

In [ ]:
date = dt.datetime.fromtimestamp(time)
date

datetime.datetime(2023, 9, 7, 8, 3, 57, 874033)

analysing times with specified distance

In [ ]:
delta = dt.timedelta(days =5)

In [ ]:
today = dt.date.today()

In [ ]:
today - delta

datetime.date(2023, 9, 2)

# map()

In [ ]:
# @title finding max between two list

lst1 = [4.6, 7.3, 2]
lst2 = [9.5, 6.73, 10]

list(map(max, lst1, lst2))

[9.5, 7.3, 10]

#lambda

In [ ]:
my_annonimous_func = lambda inp : inp ** 2

my_annonimous_func(5)

25

#list comprehensions

In [ ]:
letters = "abc"
digits = "123"

ids = [(letters[i] + letters[j] + k) for i in range(len(letters)) for j in range(i, len(letters)) for k in digits]
print(ids)
print(len(ids))

['aa1', 'aa2', 'aa3', 'ab1', 'ab2', 'ab3', 'ac1', 'ac2', 'ac3', 'bb1', 'bb2', 'bb3', 'bc1', 'bc2', 'bc3', 'cc1', 'cc2', 'cc3']
18


#Numpy

In [ ]:
#@title importing libraries
import numpy as np
import math

In [ ]:
#@title creating arrays

test_array = np.array([1, 2, 3, 4])
print(test_array)
print(test_array.ndim)

[1 2 3 4]
1


In [ ]:
#@title 2d array

two_d_array = np.array([[1, 2, 3], [5, 3, 7.9]])

print(two_d_array.ndim)

2


In [ ]:
#@title shape of an array

two_d_array.shape

(2, 3)

In [ ]:
two_d_array.dtype

dtype('float64')

##place holders

In [ ]:
#@title filling array with ones

np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#@title filling array with zeros

np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#@title filling with random uniform numbers between 0 up to 1

np.random.rand(2, 3)

array([[0.8580616 , 0.11067739, 0.4607176 ],
       [0.36152515, 0.49887376, 0.56040644]])

##sequence of numbers

In [ ]:
#@title sequence of numbers with defines step(end excluded)

np.arange(10, 50, 2)# even numbers from 10 to 48

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
#@title sequence of numers(float) with defined quantitie

np.linspace(0, 2, 15)# generaiting 15 float numbers betweeen 0 to 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

##Array oparaitions

So, we can do many things on arrays, such as mathematical manipulation, addition, subtraction, square, exponents, as well as Boolean arrays, which are binary values. And we can also do matrix manipulations, such as product transpose, inverse and so forth

In [ ]:
#@title arithmetic applied on asrray elementwise

a = np.array([[1, 2, 3], [3, 5, 6]])
b = np.array([[4.6, 2.3, 7.8], [5, 6.2, 9.0]])

print("sum of a and b : {}".format(a + b))

print("subtraction of b and : {}".format(b - a))

print("a to the power of b :{}".format(a ** b))

print("multiplicationn of a and b : {}".format(a * b))

sum of a and b : [[ 5.6  4.3 10.8]
 [ 8.  11.2 15. ]]
subtraction of b and : [[3.6 0.3 4.8]
 [2.  1.2 3. ]]
a to the power of b :[[1.00000000e+00 4.92457765e+00 5.26678739e+03]
 [2.43000000e+02 2.15582760e+04 1.00776960e+07]]
multiplicationn of a and b : [[ 4.6  4.6 23.4]
 [15.  31.  54. ]]


In [ ]:
#@title non_elemnt wise matrix multiplication

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[6, 7], [9, 0]])

print(m1@m2)

[[24  7]
 [54 21]]


###example
convert array of farenheit to celcius

In [ ]:
farenheit = np.array([10, 0, -0.5, 3, 5])#creating an array of tempreture in farenheit

celcius = (farenheit - 32) * (5 / 9)

print(celcius)

[-12.22222222 -17.77777778 -18.05555556 -16.11111111 -15.        ]


###boolean array
Another useful and important manipulation is the Boolean array. We can apply an operator on an array and a Boolean array will be returned for any element in the original with true being emitted if it meets the condition. For instance, if we want to get a Boolean array to check the Celsius degrees that are greater than minus 20 degrees, we will just say Celsius is greater than minus 20

In [ ]:
print(celcius < -17)

[False  True  True False False]


###aggregation functions

Now, numpy arrays also have an interesting aggregation functions on them, such as sum, max, min and mean

In [ ]:
array1 = np.array([[1, 3], 4])

array2 = np.array([[3, 3], [9, 5]])

array3 = np.array([[4, 5, 6], [7, 6]])

<ipython-input-18-370403693bad>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1 = np.array([[1, 3], 4])
<ipython-input-18-370403693bad>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array3 = np.array([[4, 5, 6], [7, 6]])


In [ ]:
#@title sum()

print(array3)
print(array3.sum())

print(array2)
print(array2.sum())

print(array1)
print(array1.sum())

[list([4, 5, 6]) list([7, 6])]
[4, 5, 6, 7, 6]
[[3 3]
 [9 5]]
20
[list([1, 3]) 4]


TypeError: ignored

In [ ]:
#@title max and min

print(array2)
print(array2.min(), array2.max())

print(array3)#[[4, 5, 6], [7, 6]]
print(array3.min(), array3.max())

array4 = np.array([[7, 6, 8], [7, 6]])
print(array4.min(), array4.max())

print(array1)
print(array1.min(), array1.max())

[[3 3]
 [9 5]]
3 9
[list([4, 5, 6]) list([7, 6])]
[4, 5, 6] [7, 6]
[7, 6] [7, 6, 8]
[list([1, 3]) 4]


<ipython-input-34-c842755f449c>:9: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array4 = np.array([[7, 6, 8], [7, 6]])


TypeError: ignored

In [ ]:
#@title mean()

print(array2)
print(array2.mean())

print(array3)
print(array3.mean())


print(array1)
print(array1.mean())

[[3 3]
 [9 5]]
5.0
[list([4, 5, 6]) list([7, 6])]
[2.  2.5 3.  3.5 3. ]
[list([1, 3]) 4]


TypeError: ignored

##indexing , slicing and itteraiting

###indexing

In [ ]:
array = np.array([[1, 2, 3], [2, 4, 1], [3, 14, 13.2]])

In [ ]:
array[1, 2]

1.0

In [ ]:
array[[0, 1], [2, 1]]

array([3., 4.])

####boolean indexing

In [ ]:
array[array >= 4]

array([ 4. , 14. , 13.2])

###slicing

It's important to realize that a slice of an array is a view into the same data. This is really important, this is called passing by reference. So, modifying the sub array will consequently modify the original array as well.

In [ ]:
array = np.array([[1, 2, 3], [2, 4, 1], [3, 14, 13.2]])

In [ ]:
array[0]

array([1., 2., 3.])

In [ ]:
array[:, 2:]

array([[ 3. ],
       [ 1. ],
       [13.2]])

In [ ]:
a = array[:, 2:]

a[1,0] = 100

array

array([[  1. ,   2. ,   3. ],
       [  2. ,   4. , 100. ],
       [  3. ,  14. ,  13.2]])

## working with datasets